using System.Globalization;

namespace DriveScan.Services;

public enum Language { EN, DE, FR, ES, JA, ZH, RU }

public static class L10n
{
    private static Language _current;
    public static Language Current
    {
        get => _current;
        set { _current = value; LanguageChanged?.Invoke(); }
    }

    public static event Action? LanguageChanged;

    static L10n() { _current = DetectSystemLanguage(); }

    public static Language DetectSystemLanguage()
    {
        var c = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
        return c switch { "de" => Language.DE, "fr" => Language.FR, "es" => Language.ES, "ja" => Language.JA, "zh" => Language.ZH, "ru" => Language.RU, _ => Language.EN };
    }

    public static string Get(string key)
    {
        if (S.TryGetValue(key, out var t) && t.TryGetValue(_current, out var v)) return v;
        if (S.TryGetValue(key, out t) && t.TryGetValue(Language.EN, out v)) return v;
        return key;
    }

    public static string Format(string key, params object[] args) => string.Format(Get(key), args);

    private static readonly Dictionary<string, Dictionary<Language, string>> S = new()
    {
        ["Analysis"] = new() { [Language.EN]="Analysis", [Language.DE]="Analyse", [Language.FR]="Analyse", [Language.ES]="Análisis", [Language.JA]="分析", [Language.ZH]="分析", [Language.RU]="Анализ" },
        ["View"] = new() { [Language.EN]="View", [Language.DE]="Ansicht", [Language.FR]="Affichage", [Language.ES]="Vista", [Language.JA]="表示", [Language.ZH]="视图", [Language.RU]="Вид" },
        ["Help"] = new() { [Language.EN]="Help", [Language.DE]="Hilfe", [Language.FR]="Aide", [Language.ES]="Ayuda", [Language.JA]="ヘルプ", [Language.ZH]="帮助", [Language.RU]="Помощь" },
        ["LanguageMenu"] = new() { [Language.EN]="Language", [Language.DE]="Sprache", [Language.FR]="Langue", [Language.ES]="Idioma", [Language.JA]="言語", [Language.ZH]="语言", [Language.RU]="Язык" },
        ["TopLargestFiles"] = new() { [Language.EN]="Top 50 largest files", [Language.DE]="Top 50 groesste Dateien", [Language.FR]="Top 50 plus gros fichiers", [Language.ES]="Top 50 archivos más grandes", [Language.JA]="最大ファイルTop50", [Language.ZH]="最大文件前50", [Language.RU]="Топ 50 крупнейших файлов" },
        ["OldFiles2"] = new() { [Language.EN]="Old files (> 2 years, > 1MB)", [Language.DE]="Alte Dateien (> 2 Jahre, > 1MB)", [Language.FR]="Anciens fichiers (> 2 ans, > 1Mo)", [Language.ES]="Archivos antiguos (> 2 años, > 1MB)", [Language.JA]="古いファイル（2年以上）", [Language.ZH]="旧文件（>2年）", [Language.RU]="Старые файлы (> 2 лет)" },
        ["OldFiles5"] = new() { [Language.EN]="Old files (> 5 years, > 1MB)", [Language.DE]="Alte Dateien (> 5 Jahre, > 1MB)", [Language.FR]="Anciens fichiers (> 5 ans, > 1Mo)", [Language.ES]="Archivos antiguos (> 5 años, > 1MB)", [Language.JA]="古いファイル（5年以上）", [Language.ZH]="旧文件（>5年）", [Language.RU]="Старые файлы (> 5 лет)" },
        ["TempCache"] = new() { [Language.EN]="Find Temp/Cache folders", [Language.DE]="Temp/Cache-Ordner finden", [Language.FR]="Trouver dossiers Temp/Cache", [Language.ES]="Buscar carpetas Temp/Cache", [Language.JA]="Temp/Cache検索", [Language.ZH]="查找临时/缓存", [Language.RU]="Найти Temp/Cache" },
        ["Duplicates"] = new() { [Language.EN]="Find duplicates (may take a while)", [Language.DE]="Duplikate suchen (kann dauern)", [Language.FR]="Chercher doublons", [Language.ES]="Buscar duplicados", [Language.JA]="重複ファイル検索", [Language.ZH]="查找重复文件", [Language.RU]="Поиск дубликатов" },
        ["ColorDefault"] = new() { [Language.EN]="Colors: Default", [Language.DE]="Farben: Standard", [Language.FR]="Couleurs: Standard", [Language.ES]="Colores: Estándar", [Language.JA]="色：標準", [Language.ZH]="颜色：默认", [Language.RU]="Цвета: Стандартные" },
        ["ColorFileType"] = new() { [Language.EN]="Colors: by file type", [Language.DE]="Farben: nach Dateityp", [Language.FR]="Couleurs: par type", [Language.ES]="Colores: por tipo", [Language.JA]="色：種類別", [Language.ZH]="颜色：按类型", [Language.RU]="Цвета: по типу" },
        ["ColorAge"] = new() { [Language.EN]="Colors: by age", [Language.DE]="Farben: nach Alter", [Language.FR]="Couleurs: par ancienneté", [Language.ES]="Colores: por antigüedad", [Language.JA]="色：年齢別", [Language.ZH]="颜色：按时间", [Language.RU]="Цвета: по возрасту" },
        ["FileListOff"] = new() { [Language.EN]="File list off", [Language.DE]="Dateiliste aus", [Language.FR]="Liste désactivée", [Language.ES]="Lista desactivada", [Language.JA]="リストオフ", [Language.ZH]="列表关闭", [Language.RU]="Список выкл." },
        ["FileListSize"] = new() { [Language.EN]="File list: Name + Size", [Language.DE]="Dateiliste: Name + Groesse", [Language.FR]="Liste: Nom + Taille", [Language.ES]="Lista: Nombre + Tamaño", [Language.JA]="リスト：名前+サイズ", [Language.ZH]="列表：名+大小", [Language.RU]="Список: Имя + Размер" },
        ["FileListSizeDate"] = new() { [Language.EN]="File list: Name + Size + Date", [Language.DE]="Dateiliste: Name + Groesse + Datum", [Language.FR]="Liste: Nom + Taille + Date", [Language.ES]="Lista: Nombre + Tamaño + Fecha", [Language.JA]="リスト：名前+サイズ+日付", [Language.ZH]="列表：名+大小+日期", [Language.RU]="Список: Имя + Размер + Дата" },
        ["Legend"] = new() { [Language.EN]="Legend: File type colors", [Language.DE]="Legende: Dateityp-Farben", [Language.FR]="Légende: Couleurs", [Language.ES]="Leyenda: Colores", [Language.JA]="凡例", [Language.ZH]="图例", [Language.RU]="Легенда" },
        ["About"] = new() { [Language.EN]="About disk0...", [Language.DE]="Ueber disk0...", [Language.FR]="À propos de disk0...", [Language.ES]="Acerca de disk0...", [Language.JA]="disk0について", [Language.ZH]="关于disk0", [Language.RU]="О disk0..." },
        ["Drive"] = new() { [Language.EN]="Drive:", [Language.DE]="Laufwerk:", [Language.FR]="Lecteur:", [Language.ES]="Unidad:", [Language.JA]="ドライブ:", [Language.ZH]="驱动器:", [Language.RU]="Диск:" },
        ["ViewMode"] = new() { [Language.EN]="View:", [Language.DE]="Ansicht:", [Language.FR]="Vue:", [Language.ES]="Vista:", [Language.JA]="表示:", [Language.ZH]="视图:", [Language.RU]="Вид:" },
        ["Sunburst"] = new() { [Language.EN]="Sunburst (Circle)", [Language.DE]="Sunburst (Kreis)", [Language.FR]="Sunburst (Cercle)", [Language.ES]="Sunburst (Círculo)", [Language.JA]="サンバースト", [Language.ZH]="旭日图", [Language.RU]="Санберст" },
        ["Treemap"] = new() { [Language.EN]="Treemap (Rectangle)", [Language.DE]="Treemap (Rechteck)", [Language.FR]="Treemap (Rectangle)", [Language.ES]="Treemap (Rectángulo)", [Language.JA]="ツリーマップ", [Language.ZH]="矩形树图", [Language.RU]="Карта дерева" },
        ["DepthLabel"] = new() { [Language.EN]="Depth:", [Language.DE]="Tiefe:", [Language.FR]="Prof.:", [Language.ES]="Prof.:", [Language.JA]="深さ:", [Language.ZH]="深度:", [Language.RU]="Глуб.:" },
        ["Scan"] = new() { [Language.EN]="Scan", [Language.DE]="Scannen", [Language.FR]="Scanner", [Language.ES]="Escanear", [Language.JA]="スキャン", [Language.ZH]="扫描", [Language.RU]="Скан" },
        ["Back"] = new() { [Language.EN]="Back", [Language.DE]="Zurueck", [Language.FR]="Retour", [Language.ES]="Atrás", [Language.JA]="戻る", [Language.ZH]="返回", [Language.RU]="Назад" },
        ["Stop"] = new() { [Language.EN]="Stop", [Language.DE]="Stopp", [Language.FR]="Stop", [Language.ES]="Detener", [Language.JA]="停止", [Language.ZH]="停止", [Language.RU]="Стоп" },
        ["Total"] = new() { [Language.EN]="Total:", [Language.DE]="Gesamt:", [Language.FR]="Total:", [Language.ES]="Total:", [Language.JA]="合計:", [Language.ZH]="总计:", [Language.RU]="Всего:" },
        ["Used"] = new() { [Language.EN]="Used:", [Language.DE]="Belegt:", [Language.FR]="Utilisé:", [Language.ES]="Usado:", [Language.JA]="使用:", [Language.ZH]="已用:", [Language.RU]="Занято:" },
        ["Free"] = new() { [Language.EN]="Free:", [Language.DE]="Frei:", [Language.FR]="Libre:", [Language.ES]="Libre:", [Language.JA]="空き:", [Language.ZH]="可用:", [Language.RU]="Свободно:" },
        ["Files"] = new() { [Language.EN]="Files", [Language.DE]="Dateien", [Language.FR]="Fichiers", [Language.ES]="Archivos", [Language.JA]="ファイル", [Language.ZH]="文件", [Language.RU]="Файлы" },
        ["Subdirs"] = new() { [Language.EN]="Subdirs", [Language.DE]="Unterverz.", [Language.FR]="Sous-rép.", [Language.ES]="Subdirs.", [Language.JA]="サブディレクトリ", [Language.ZH]="子目录", [Language.RU]="Подкат." },
        ["Dirs"] = new() { [Language.EN]="Dirs", [Language.DE]="Verz.", [Language.FR]="Rép.", [Language.ES]="Dirs.", [Language.JA]="ディレクトリ", [Language.ZH]="目录", [Language.RU]="Кат." },
        ["ScanProgress"] = new() { [Language.EN]="Scanning... {0}%", [Language.DE]="Scanne... {0}%", [Language.FR]="Analyse... {0}%", [Language.ES]="Escaneando... {0}%", [Language.JA]="スキャン中... {0}%", [Language.ZH]="扫描中... {0}%", [Language.RU]="Скан... {0}%" },
        ["Done"] = new() { [Language.EN]="Done", [Language.DE]="Fertig", [Language.FR]="Terminé", [Language.ES]="Listo", [Language.JA]="完了", [Language.ZH]="完成", [Language.RU]="Готово" },
        ["RecycleBin"] = new() { [Language.EN]="Recycle Bin", [Language.DE]="Papierkorb", [Language.FR]="Corbeille", [Language.ES]="Papelera", [Language.JA]="ごみ箱", [Language.ZH]="回收站", [Language.RU]="Корзина" },
        ["OpenExplorer"] = new() { [Language.EN]="Open in Explorer", [Language.DE]="Im Explorer oeffnen", [Language.FR]="Ouvrir dans l'Explorateur", [Language.ES]="Abrir en Explorador", [Language.JA]="エクスプローラーで開く", [Language.ZH]="在资源管理器中打开", [Language.RU]="Открыть в проводнике" },
        ["ZoomIn"] = new() { [Language.EN]="Zoom in:", [Language.DE]="Hineinzoomen:", [Language.FR]="Zoomer:", [Language.ES]="Acercar:", [Language.JA]="ズームイン:", [Language.ZH]="放大:", [Language.RU]="Увеличить:" },
        ["BackToOverview"] = new() { [Language.EN]="Back to overview", [Language.DE]="Zurueck zur Uebersicht", [Language.FR]="Retour à la vue d'ensemble", [Language.ES]="Volver a vista general", [Language.JA]="概要に戻る", [Language.ZH]="返回概览", [Language.RU]="Вернуться к обзору" },
        ["EmptyRecycleBin"] = new() { [Language.EN]="Empty Recycle Bin", [Language.DE]="Papierkorb leeren", [Language.FR]="Vider la corbeille", [Language.ES]="Vaciar papelera", [Language.JA]="ごみ箱を空にする", [Language.ZH]="清空回收站", [Language.RU]="Очистить корзину" },
        ["DeleteDir"] = new() { [Language.EN]="Delete directory:", [Language.DE]="Verzeichnis loeschen:", [Language.FR]="Supprimer:", [Language.ES]="Eliminar:", [Language.JA]="削除:", [Language.ZH]="删除:", [Language.RU]="Удалить:" },
        ["DeleteConfirm"] = new() { [Language.EN]="Really delete this directory?", [Language.DE]="Verzeichnis wirklich loeschen?", [Language.FR]="Vraiment supprimer?", [Language.ES]="¿Realmente eliminar?", [Language.JA]="本当に削除しますか？", [Language.ZH]="确定删除？", [Language.RU]="Удалить каталог?" },
        ["DeleteWarning"] = new() { [Language.EN]="WARNING: Cannot be undone!", [Language.DE]="ACHTUNG: Nicht rueckgaengig machbar!", [Language.FR]="ATTENTION: Irréversible!", [Language.ES]="¡No se puede deshacer!", [Language.JA]="警告：元に戻せません！", [Language.ZH]="警告：不可撤消！", [Language.RU]="Нельзя отменить!" },
        ["Deleted"] = new() { [Language.EN]="Deleted", [Language.DE]="Geloescht", [Language.FR]="Supprimé", [Language.ES]="Eliminado", [Language.JA]="削除済み", [Language.ZH]="已删除", [Language.RU]="Удалено" },
        ["DeletedRescan"] = new() { [Language.EN]="Deleted. Please rescan.", [Language.DE]="Geloescht. Bitte erneut scannen.", [Language.FR]="Supprimé. Rescanner SVP.", [Language.ES]="Eliminado. Reescanear.", [Language.JA]="削除済み。再スキャンしてください。", [Language.ZH]="已删除。请重新扫描。", [Language.RU]="Удалено. Пересканируйте." },
        ["EmptyBinConfirm"] = new() { [Language.EN]="Empty Recycle Bin?\nAll files permanently deleted.", [Language.DE]="Papierkorb leeren?\nAlle Dateien endgueltig geloescht.", [Language.FR]="Vider la corbeille?\nSuppression définitive.", [Language.ES]="¿Vaciar papelera?\nEliminación permanente.", [Language.JA]="ごみ箱を空にしますか？", [Language.ZH]="清空回收站？", [Language.RU]="Очистить корзину?" },
        ["Error"] = new() { [Language.EN]="Error", [Language.DE]="Fehler", [Language.FR]="Erreur", [Language.ES]="Error", [Language.JA]="エラー", [Language.ZH]="错误", [Language.RU]="Ошибка" },
        ["ErrorDeleting"] = new() { [Language.EN]="Error deleting:", [Language.DE]="Fehler beim Loeschen:", [Language.FR]="Erreur:", [Language.ES]="Error:", [Language.JA]="エラー:", [Language.ZH]="删除错误:", [Language.RU]="Ошибка:" },
        ["Results"] = new() { [Language.EN]="Results", [Language.DE]="Ergebnisse", [Language.FR]="Résultats", [Language.ES]="Resultados", [Language.JA]="結果", [Language.ZH]="结果", [Language.RU]="Результаты" },
        ["TotalSize"] = new() { [Language.EN]="Total:", [Language.DE]="Gesamt:", [Language.FR]="Total:", [Language.ES]="Total:", [Language.JA]="合計:", [Language.ZH]="总计:", [Language.RU]="Всего:" },
        ["SearchRunning"] = new() { [Language.EN]="Searching...", [Language.DE]="Suche laeuft...", [Language.FR]="Recherche...", [Language.ES]="Buscando...", [Language.JA]="検索中...", [Language.ZH]="搜索中...", [Language.RU]="Поиск..." },
        ["Close"] = new() { [Language.EN]="Close", [Language.DE]="Schliessen", [Language.FR]="Fermer", [Language.ES]="Cerrar", [Language.JA]="閉じる", [Language.ZH]="关闭", [Language.RU]="Закрыть" },
        ["Size"] = new() { [Language.EN]="Size", [Language.DE]="Groesse", [Language.FR]="Taille", [Language.ES]="Tamaño", [Language.JA]="サイズ", [Language.ZH]="大小", [Language.RU]="Размер" },
        ["Details"] = new() { [Language.EN]="Details", [Language.DE]="Details", [Language.FR]="Détails", [Language.ES]="Detalles", [Language.JA]="詳細", [Language.ZH]="详情", [Language.RU]="Детали" },
        ["Category"] = new() { [Language.EN]="Category", [Language.DE]="Kategorie", [Language.FR]="Catégorie", [Language.ES]="Categoría", [Language.JA]="カテゴリ", [Language.ZH]="类别", [Language.RU]="Категория" },
        ["Name"] = new() { [Language.EN]="Name", [Language.DE]="Name", [Language.FR]="Nom", [Language.ES]="Nombre", [Language.JA]="名前", [Language.ZH]="名称", [Language.RU]="Имя" },
        ["Disclaimer"] = new()
        {
            [Language.EN]="disk0 v1.1 \u2013 Freeware\n\u00A9 CSBG.BIZ \u2013 All rights reserved.\n\nThis software is provided \u201Cas is\u201D without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, or non-infringement. Use is entirely at your own risk. The author shall not be liable for any damages, data loss, or other disadvantages arising directly or indirectly from the use or inability to use this software. Source code is available upon request.\n\nContact: disk0@csbg.biz",
            [Language.DE]="disk0 v1.1 \u2013 Freeware\n\u00A9 CSBG.BIZ \u2013 Alle Rechte vorbehalten.\n\nDiese Software wird \u201Ewie besehen\u201C ohne jegliche ausdrueckliche oder stillschweigende Gewaehrleistung bereitgestellt, einschliesslich, aber nicht beschraenkt auf die Gewaehrleistung der Marktgaengigkeit, Eignung fuer einen bestimmten Zweck oder Nichtverletzung von Rechten Dritter. Die Nutzung erfolgt ausschliesslich auf eigene Gefahr. Der Autor uebernimmt keinerlei Haftung fuer Schaeden, Datenverlust oder sonstige Nachteile, die direkt oder indirekt aus der Nutzung oder der Unmoeglichkeit der Nutzung dieser Software entstehen. Der Quellcode kann auf Anfrage zur Verfuegung gestellt werden.\n\nKontakt: disk0@csbg.biz",
            [Language.FR]="disk0 v1.1 \u2013 Freeware\n\u00A9 CSBG.BIZ \u2013 Tous droits r\u00E9serv\u00E9s.\n\nCe logiciel est fourni \u00AB tel quel \u00BB sans garantie d'aucune sorte, expresse ou implicite. L'utilisation est enti\u00E8rement \u00E0 vos risques et p\u00E9rils. L'auteur ne saurait \u00EAtre tenu responsable de tout dommage ou perte de donn\u00E9es. Code source disponible sur demande.\n\nContact: disk0@csbg.biz",
            [Language.ES]="disk0 v1.1 \u2013 Freeware\n\u00A9 CSBG.BIZ \u2013 Todos los derechos reservados.\n\nEste software se proporciona \u201Ctal cual\u201D sin garant\u00EDa de ning\u00FAn tipo, expresa o impl\u00EDcita. El uso es bajo su propio riesgo. El autor no ser\u00E1 responsable de ning\u00FAn da\u00F1o o p\u00E9rdida de datos. C\u00F3digo fuente disponible a pedido.\n\nContacto: disk0@csbg.biz",
            [Language.JA]="disk0 v1.1 \u2013 \u30D5\u30EA\u30FC\u30A6\u30A7\u30A2\n\u00A9 CSBG.BIZ \u2013 \u5168\u8457\u4F5C\u6A29\u6240\u6709\u3002\n\n\u672C\u30BD\u30D5\u30C8\u30A6\u30A7\u30A2\u306F\u3001\u660E\u793A\u7684\u307E\u305F\u306F\u9ED9\u793A\u7684\u3092\u554F\u308F\u305A\u3001\u3044\u304B\u306A\u308B\u4FDD\u8A3C\u3082\u306A\u304F\u300C\u73FE\u72B6\u306E\u307E\u307E\u300D\u63D0\u4F9B\u3055\u308C\u307E\u3059\u3002\u4F7F\u7528\u306F\u5B8C\u5168\u306B\u81EA\u5DF1\u8CAC\u4EFB\u3067\u3059\u3002\u30BD\u30FC\u30B9\u30B3\u30FC\u30C9\u306F\u30EA\u30AF\u30A8\u30B9\u30C8\u306B\u5FDC\u3058\u3066\u63D0\u4F9B\u3002\n\n\u9023\u7D61\u5148: disk0@csbg.biz",
            [Language.ZH]="disk0 v1.1 \u2013 \u514D\u8D39\u8F6F\u4EF6\n\u00A9 CSBG.BIZ \u2013 \u7248\u6743\u6240\u6709\u3002\n\n\u672C\u8F6F\u4EF6\u6309\u201C\u539F\u6837\u201D\u63D0\u4F9B\uFF0C\u4E0D\u63D0\u4F9B\u4EFB\u4F55\u660E\u793A\u6216\u6697\u793A\u7684\u4FDD\u8BC1\u3002\u4F7F\u7528\u98CE\u9669\u81EA\u8D1F\u3002\u6E90\u4EE3\u7801\u53EF\u5E94\u8981\u6C42\u63D0\u4F9B\u3002\n\n\u8054\u7CFB: disk0@csbg.biz",
            [Language.RU]="disk0 v1.1 \u2013 \u0411\u0435\u0441\u043F\u043B\u0430\u0442\u043D\u043E\u0435 \u041F\u041E\n\u00A9 CSBG.BIZ \u2013 \u0412\u0441\u0435 \u043F\u0440\u0430\u0432\u0430 \u0437\u0430\u0449\u0438\u0449\u0435\u043D\u044B.\n\n\u041F\u041E \u043F\u0440\u0435\u0434\u043E\u0441\u0442\u0430\u0432\u043B\u044F\u0435\u0442\u0441\u044F \u00AB\u043A\u0430\u043A \u0435\u0441\u0442\u044C\u00BB \u0431\u0435\u0437 \u043A\u0430\u043A\u0438\u0445-\u043B\u0438\u0431\u043E \u0433\u0430\u0440\u0430\u043D\u0442\u0438\u0439. \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u043D\u0438\u0435 \u043D\u0430 \u0441\u0432\u043E\u0439 \u0440\u0438\u0441\u043A. \u0418\u0441\u0445\u043E\u0434\u043D\u044B\u0439 \u043A\u043E\u0434 \u043F\u043E \u0437\u0430\u043F\u0440\u043E\u0441\u0443.\n\n\u041A\u043E\u043D\u0442\u0430\u043A\u0442: disk0@csbg.biz"
        },
        ["AutoScanOnStart"] = new() { [Language.EN]="Auto-scan on start", [Language.DE]="Automatisch scannen beim Start", [Language.FR]="Scan auto au démarrage", [Language.ES]="Escaneo automático al iniciar", [Language.JA]="起動時に自動スキャン", [Language.ZH]="启动时自动扫描", [Language.RU]="Автоскан при запуске" },
        ["DisclaimerTitle"] = new() { [Language.EN]="License Agreement", [Language.DE]="Lizenzvereinbarung", [Language.FR]="Accord de licence", [Language.ES]="Acuerdo de licencia", [Language.JA]="ライセンス契約", [Language.ZH]="许可协议", [Language.RU]="Лицензионное соглашение" },
        ["DisclaimerAccept"] = new() { [Language.EN]="Do you accept these terms?", [Language.DE]="Akzeptieren Sie diese Bedingungen?", [Language.FR]="Acceptez-vous ces conditions?", [Language.ES]="¿Acepta estos términos?", [Language.JA]="これらの条件に同意しますか？", [Language.ZH]="您接受这些条款吗？", [Language.RU]="Вы принимаете эти условия?" },
        ["DeleteCandidates"] = new() { [Language.EN]="Find delete candidates", [Language.DE]="Loeschkandidaten finden", [Language.FR]="Candidats à la suppression", [Language.ES]="Candidatos para eliminar", [Language.JA]="削除候補を検索", [Language.ZH]="查找删除候选", [Language.RU]="Кандидаты на удаление" },
        ["NetworkPath"] = new() { [Language.EN]="Network path (e.g. \\\\server\\share):", [Language.DE]="Netzwerkpfad (z.B. \\\\server\\share):", [Language.FR]="Chemin réseau:", [Language.ES]="Ruta de red:", [Language.JA]="ネットワークパス:", [Language.ZH]="网络路径:", [Language.RU]="Сетевой путь:" },
        ["AddNetwork"] = new() { [Language.EN]="Add network path...", [Language.DE]="Netzwerkpfad hinzufuegen...", [Language.FR]="Ajouter chemin réseau...", [Language.ES]="Agregar ruta de red...", [Language.JA]="ネットワークパス追加...", [Language.ZH]="添加网络路径...", [Language.RU]="Добавить сетевой путь..." },
        ["AnalysisScope"] = new() { [Language.EN]="Scope: {0}", [Language.DE]="Bereich: {0}", [Language.FR]="Portée: {0}", [Language.ES]="Alcance: {0}", [Language.JA]="範囲: {0}", [Language.ZH]="范围: {0}", [Language.RU]="Область: {0}" },
        ["HelpText"] = new()
        {
            [Language.EN]="disk0 - Disk Space Analyzer\n\nMain Functions:\n- Sunburst/Treemap visualization of disk usage\n- Click directories to see details, right-click for options\n- Zoom into subdirectories, navigate back\n- Color modes: Default, File Type, Age\n\nAnalysis Tools (Menu > Analysis):\nAll analysis runs on the selected directory and all subdirectories.\n- Top 50 Largest Files: Finds the biggest space consumers\n- Old Files: Files not modified in 2/5+ years (>1MB)\n- Temp/Cache: Detects node_modules, .git, browser caches, Windows temp\n- Duplicates: Files with same size and content (partial hash)\n- Delete Candidates: temp files, logs, backups, Office temp files\n\nTips:\n- Double-click results to open in Explorer\n- Select a directory first, then run analysis on that subtree\n- Use age coloring to spot old data visually",
            [Language.DE]="disk0 - Festplatten-Analyse\n\nHauptfunktionen:\n- Sunburst/Treemap-Visualisierung des Speicherverbrauchs\n- Klick auf Verzeichnisse zeigt Details, Rechtsklick fuer Optionen\n- In Unterverzeichnisse zoomen, zurueck navigieren\n- Farbmodi: Standard, Dateityp, Alter\n\nAnalyse-Tools (Menu > Analyse):\nAlle Analysen laufen auf dem gewaehlten Verzeichnis und allen Unterverzeichnissen.\n- Top 50 groesste Dateien: Findet die groessten Platzverbraucher\n- Alte Dateien: Seit 2/5+ Jahren nicht geaendert (>1MB)\n- Temp/Cache: Erkennt node_modules, .git, Browser-Caches, Windows-Temp\n- Duplikate: Dateien mit gleicher Groesse und gleichem Inhalt\n- Loeschkandidaten: Temp-Dateien, Logs, Backups, Office-Temp\n\nTipps:\n- Doppelklick auf Ergebnisse oeffnet im Explorer\n- Erst Verzeichnis waehlen, dann Analyse auf diesem Teilbaum\n- Altersfaerbung nutzen um alte Daten visuell zu erkennen",
            [Language.FR]="disk0 - Analyseur d'espace disque\n\nFonctions principales:\n- Visualisation Sunburst/Treemap\n- Cliquez pour détails, clic droit pour options\n- Zoom dans les sous-répertoires\n\nOutils d'analyse (Menu > Analyse):\nToutes les analyses s'exécutent sur le répertoire sélectionné.\n- Plus gros fichiers\n- Anciens fichiers (2/5+ ans)\n- Dossiers Temp/Cache\n- Doublons\n- Candidats à la suppression",
            [Language.ES]="disk0 - Analizador de espacio\n\nFunciones principales:\n- Visualización Sunburst/Treemap\n- Clic para detalles, clic derecho para opciones\n\nHerramientas de análisis (Menu > Análisis):\nTodas las análisis se ejecutan en el directorio seleccionado.\n- Archivos más grandes\n- Archivos antiguos\n- Carpetas Temp/Cache\n- Duplicados\n- Candidatos para eliminar",
            [Language.JA]="disk0 - ディスク容量アナライザー\n\n主な機能:\n- Sunburst/Treemap表示\n- クリックで詳細、右クリックでオプション\n\n分析ツール（メニュー > 分析）:\n選択したディレクトリとサブディレクトリで実行。\n- 最大ファイル\n- 古いファイル\n- Temp/Cache\n- 重複ファイル\n- 削除候補",
            [Language.ZH]="disk0 - 磁盘空间分析器\n\n主要功能:\n- Sunburst/Treemap可视化\n- 点击查看详情，右键选项\n\n分析工具（菜单 > 分析）:\n在选定目录及子目录上运行。\n- 最大文件\n- 旧文件\n- 临时/缓存\n- 重复文件\n- 删除候选",
            [Language.RU]="disk0 - Анализатор дискового пространства\n\nОсновные функции:\n- Визуализация Sunburst/Treemap\n- Клик для деталей, правый клик для опций\n\nИнструменты анализа (Меню > Анализ):\nВсе анализы выполняются в выбранном каталоге.\n- Крупнейшие файлы\n- Старые файлы\n- Temp/Cache\n- Дубликаты\n- Кандидаты на удаление"
        },
        ["HelpTitle"] = new() { [Language.EN]="Help - disk0", [Language.DE]="Hilfe - disk0", [Language.FR]="Aide - disk0", [Language.ES]="Ayuda - disk0", [Language.JA]="ヘルプ - disk0", [Language.ZH]="帮助 - disk0", [Language.RU]="Помощь - disk0" },
        ["UserGuide"] = new() { [Language.EN]="User Guide", [Language.DE]="Benutzerhandbuch", [Language.FR]="Guide utilisateur", [Language.ES]="Guía de usuario", [Language.JA]="ユーザーガイド", [Language.ZH]="用户指南", [Language.RU]="Руководство" },
        ["RegisterShell"] = new() { [Language.EN]="Add to Explorer context menu", [Language.DE]="Ins Explorer-Kontextmenu eintragen", [Language.FR]="Ajouter au menu contextuel", [Language.ES]="Agregar al menú contextual", [Language.JA]="エクスプローラーメニューに追加", [Language.ZH]="添加到右键菜单", [Language.RU]="Добавить в контекстное меню" },
        ["UnregisterShell"] = new() { [Language.EN]="Remove from Explorer context menu", [Language.DE]="Aus Explorer-Kontextmenu entfernen", [Language.FR]="Retirer du menu contextuel", [Language.ES]="Quitar del menú contextual", [Language.JA]="エクスプローラーメニューから削除", [Language.ZH]="从右键菜单移除", [Language.RU]="Удалить из контекстного меню" },
        ["ShellRegistered"] = new() { [Language.EN]="Context menu entry added.\nRight-click any folder > 'Scan with disk0'", [Language.DE]="Kontextmenu-Eintrag hinzugefuegt.\nRechtsklick auf Ordner > 'Scan with disk0'", [Language.FR]="Entrée ajoutée au menu contextuel.", [Language.ES]="Entrada agregada al menú contextual.", [Language.JA]="コンテキストメニューに追加しました。", [Language.ZH]="已添加到右键菜单。", [Language.RU]="Добавлено в контекстное меню." },
        ["ShellUnregistered"] = new() { [Language.EN]="Context menu entry removed.", [Language.DE]="Kontextmenu-Eintrag entfernt.", [Language.FR]="Entrée retirée.", [Language.ES]="Entrada eliminada.", [Language.JA]="メニューから削除しました。", [Language.ZH]="已从菜单移除。", [Language.RU]="Удалено из меню." },
        ["ShellNeedAdmin"] = new() { [Language.EN]="Administrator rights required.\nPlease run disk0 as administrator.", [Language.DE]="Administratorrechte erforderlich.\nBitte disk0 als Administrator starten.", [Language.FR]="Droits administrateur requis.", [Language.ES]="Se requieren derechos de administrador.", [Language.JA]="管理者権限が必要です。", [Language.ZH]="需要管理员权限。", [Language.RU]="Требуются права администратора." },
    };
}
